# Golang version - Docker Hub (hub.docker.com)
FROM golang:alpine3.12

# Enviornment variables
ENV APP_NAME zleague-api
ENV PORT 8080

# Set open file limit
RUN ulimit -n 100000

# Open system port
EXPOSE ${PORT}

# Working directory
WORKDIR /go/src/${APP_NAME}

COPY . /go/src/${APP_NAME}

# Install dependecies from mod file
RUN go mod download

# Hot reloading for development!
RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build -o zleague-api" --command=./zleague-api